site_name: SAS Manual
site_description: Learning How to Program in SAS
site_author: Lucía Rodrigo Insausti

pages:
    - Gettin' Started!: index.md
    - The Essentials: 
      - 'Accessing Data': 'essentials/accessing.md'
      - 'Producing Detailed Reports': 'essentials/reporting.md'
      - 'Formatting Data Values': 'essentials/formatting.md'
      - 'Reading SAS Data Sets': 'essentials/reading-sas.md'
      - 'Reading Spreadsheet and Database Data': 'essentials/reading-spreadsheets.md'
      - 'Reading Raw Data Files': 'essentials/reading-raw.md'
      - 'Manipulating Data': 'essentials/manipulation.md'
      - 'Combining SAS Data Sets': 'essentials/combination.md'
      - 'Creating Summary Reports': 'essentials/summary.md'
    - Basic Statistics: 
      - 'Introduction': 'statistics/introduction.md'
      - 'Analysis of Variance (ANOVA)': 'statistics/anova.md'
      - 'Regression': 'statistics/regression.md'
      - 'Model Post-Fitting for Inference': 'statistics/inference.md'
      - 'Categorical Data Analysis': 'statistics/categorical-data.md'
      - 'Model Building and Scoring for Prediction': 'statistics/prediction.md'
      - 'Miscellanea': 'statistics/miscellanea.md'
   - Using Macros: 
      - 'Introducing Macro Variables': 'macros/introducing-macrovar.md.md'
      - 'Using Macro Functions': 'macros/using-macrofunc.md'
      - 'Creating Macro Variables at Execution Time': 'macros/macrovar-at-execution-time.md'
      - 'Creating and Using Macro Programs': 'macros/macroprog.md'
      - 'Using Conditional and Iterative Processing in Macro Programs': 'macros/macroprog-processing.md'
      - 'Debugging Options': 'macros/debugging-options.md'
      - 'More on Macro Programming': 'macros/more-macro.md'
    - SQL:
      - 'Getting Started with the SQL Procedure': 'sql/getting-started.md'
      - 'Writing Basic Queries': 'sql/basic-queries.md'
      - 'Displaying Query Results': 'sql/displaying-results.md'
      - 'Working with SQL Joins': 'sql/joins.md'
      - 'Working with Nested Queries': 'sql/nested-queries.md'
      - 'Working with Set Operators': 'sql/set-operators.md'
      - 'Creating Tables and Views': 'sql/tables-views.md'
      - 'Using Advanced PROC SQL Features': 'sql/advanced.md'
      - 'Miscellanea': 'sql/miscellanea.md'
    - Other Analysis:
      - 'Model Selection': 'other-analysis/model-selection.md'
      - 'Dealing with Missing Data': 'other-analysis/missing-data.md'
      - 'Interim Analysis Design': 'other-analysis/interim-analysis.md'
      - 'Normality Tests': 'other-analysis/normality-tests.md'
      - 'Effect Size': 'other-analysis/effect-size.md'
      - 'Propensity Score': 'other-analysis/propensity-score.md'
      - 'ROC Curve': 'other-analysis/roc-curve.md'
      - 'Sequence Design': 'other-analysis/sequence-design.md'
      - 'Survival Analysis': 'other-analysis/survival-analysis.md'
      - 'ORR and DCR': 'other-analysis/orr-dcr.md'
      - 'Clustering': 'other-analysis/clustering.md'
    - Specific Procedures:
      - 'General Notes on Regression Procedures': 'procedures/regression-models.md'
      - 'PROC GLIMMIX': 'procedures/glimmix.md'
      - 'PROC MIXED': 'procedures/mixed.md'
    - SAS Outputs:
      - 'Output Delivery System': 'sas-outputs/ods.md'
      - 'Graphs and Plots': 'sas-outputs/graphs.md'
      - 'PROC PRINT': 'sas-outputs/print.md'
      - 'PROC REPORT': 'sas-outputs/report.md'
      - 'PROC TABULATE': 'sas-outputs/tabulate.md'
      - 'PROC TEMPLATE': 'sas-outputs/template.md'
      - 'Write to pdf file': 'sas-outputs/pdf.md'
      - 'Export to Excel file': 'sas-outputs/excel.md'
    - SAS vs R: 
      - 'Introduction': 'sasvsr/introduction.md'
      - 'Importing and Reporting Data': 'sasvsr/importing-reporting.md'
      - 'Creating New Variables, Functions and Data Tables': 'sasvsr/variables-functions.md'
      - 'Random Number Generation and Plotting': 'sasvsr/random-plotting.md'
      - 'Descriptive Procedures, Output Delivery System and Macros': 'sasvsr/proc-ods-macros.md'
      - 'Analyzing the Data via Inferential Procedures': 'sasvsr/inferential.md'
      - 'Interactive Matrix Language (IML)': 'sasvsr/iml.md'
      - 'A Bridge Between SAS and R': 'sasvsr/bridge.md'
    - Using Wizard Menus: wizard.md
    - SAS Visual Analytics: sasvi.md
    - CDISC:
      - 'Introduction': 'CDISC/introduction.md'
    - Miscellanea: 
      - 'Working with Arrays': 'miscellanea/arrays.md'
      - 'Execution time': 'miscellanea/execution-time.md'
      - 'Time intervals': 'miscellanea/time-intervals.md'
      - 'Patient identification': 'miscellanea/patient-identification.md'
    - Medical terms:
      - 'General': 'medical/general.md'
      - 'Laboratory Test': 'medical/labs.md'
      - 'Treatment Exposure': 'medical/exposure.md'
    - R with Shiny:
      - 'Introduction and Shiny Basics': 'R-with-Shiny/introduction.md'
      - 'Inputs, Outputs, and Rendering Functions': 'R-with-Shiny/input-output.md'
      - 'Reactive Programming': 'R-with-Shiny/reactive.md'
      - 'Customizing Appearance': 'R-with-Shiny/custom.md'

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
    - js/mathjaxhelper.js

markdown_extensions:
    - mdx_math
    - admonition
    - codehilite(linenums=true)
    - toc(permalink=true)

theme: 'material'
