site_name: SAS Manual
site_description: Learning How to Program in SAS
site_author: Lucía Rodrigo Insausti

pages:
    - Gettin' Started!: index.md
    - The Essentials: 
      - 'Accessing Data': 'essentials/accessing.md'
      - 'Producing Detailed Reports': 'essentials/reporting.md'
      - 'Formatting Data Values': 'essentials/formatting.md'
      - 'Reading SAS Data Sets': 'essentials/reading-sas.md'
      - 'Reading Spreadsheet and Database Data': 'essentials/reading-spreadsheets.md'
      - 'Reading Raw Data Files': 'essentials/reading-raw.md'
      - 'Manipulating Data': 'essentials/manipulation.md'
      - 'Combining SAS Data Sets': 'essentials/combination.md'
      - 'Creating Summary Reports': 'essentials/summary.md'
    - Basic Statistics: 
      - 'Introduction': 'statistics/introduction.md'
      - 'Analysis of Variance (ANOVA)': 'statistics/anova.md'
      - 'Regression': 'statistics/regression.md'
      - 'Model Post-Fitting for Inference': 'statistics/inference.md'
      - 'Categorical Data Analysis': 'statistics/categorical-data.md'
      - 'Model Building and Scoring for Prediction': 'statistics/prediction.md'
      - 'Miscellanea': 'statistics/miscellanea.md'
    - Other Analysis:
      - 'Dealing with Missing Data': 'other-analysis/missing-data.md'
      - 'Interim Analysis Design': 'other-analysis/interim-analysis.md'
      - 'Normality tests': 'other-analysis/normality-tests.md'
      - 'Propensity Score': 'other-analysis/propensity-score.md'
      - 'ROC curve': 'other-analysis/roc-curve.md'
      - 'Survival Analysis': 'other-analysis/survival-analysis.md'
      - 'Clustering': 'other-analysis/clustering.md'
    - Specific Procedures:
      - 'General notes on regression procedures': 'procedures/regression-models.md'
      - 'PROC GLIMMIX': 'procedures/glimmix.md'
      - 'PROC MIXED': 'procedures/mixed.md'
      - 'PROC SQL': 'procedures/sql.md'
    - SAS Outputs:
      - 'Reports': 'sas-outputs/reports.md'
      - 'Graphs and Plots': 'sas-outputs/graphs.md'
      - 'PROC PRINT': 'sas-outputs/print.md'
      - 'PROC REPORT': 'sas-outputs/report.md'
      - 'PROC TABULATE': 'sas-outputs/tabulate.md'
      - 'PROC TEMPLATE': 'sas-outputs/template.md'
    - Using Macros: macros.md
    - Using Wizard Menus: wizard.md
    - SAS Visual Analytics: sasvi.md
    - Miscellanea: 
      - 'Working with Arrays': 'miscellanea/arrays.md'
      - 'Execution time': 'miscellanea/execution-time.md'
      - 'Patient identification': 'miscellanea/patient-identification.md'

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
    - js/mathjaxhelper.js
    - superfences

markdown_extensions:
    - mdx_math
    - admonition
    - codehilite(linenums=true)
    - toc(permalink=true)

theme: 'material'
