site_name: SAS Manual
site_description: Learning How to Program in SAS
site_author: Lucía Rodrigo Insausti

pages:
    - Gettin' Started!: index.md
    - The Essentials: essentials.md
    - Basic Statistics: 
      - 'Introduction': 'statistics/introduction.md'
      - 'Analysis of Variance (ANOVA)': 'statistics/anova.md'
      - 'Regression': 'statistics/regression.md'
      - 'Model Post-Fitting for Inference': 'statistics/inference.md'
      - 'Categorical Data Analysis': 'statistics/categorical-data.md'
      - 'Model Building and Scoring for Prediction': 'statistics/prediction.md'
    - Dealing with Missing Data: missing_data.md
    - Using Macros: macros.md
    - Miscellanea: miscellanea.md

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
    - js/mathjaxhelper.js

markdown_extensions:
    - mdx_math
    - admonition
    - codehilite(linenums=true)
    - toc(permalink=true)

theme: 'material'
